### ISSUE TITLE
Error v1.7.1

### ISSUE THREAD

**Issue by yochilllllllll** [RTO-Websites/dynamic-conditions#80]
Updated to version 1.7.1 and it messed up the formatting & other elements of my website. Deactivated plugin and it goes back to normal. See attached screenshot.

PHP 7.4.33
Wordpress 6.6.1

No issues with previous version 1.6.3 prior to this update. 
Rolling back to 1.6.3 now causes fatal error on staging site.
Rolling back to 1.6.2 functions correctly.

<img width="1440" alt="Screen Shot 2024-08-08 at 11 32 08 PM" src="https://github.com/user-attachments/assets/f044536c-410e-4fd7-ac91-b564779883d9">

**Comment by crazypsycho** [comment]
Can you make a screenshot of the dynamic-conditions-settings of the widget and activate debug-mode and make a screenshot of the debug-output?

Or could you provide login-data for your staging-page, so i can have a look?

**Comment by jakobspodsberg** [comment]
got the same issue.

We rolled back to 1.6.2

Our debug.log:
[09-Aug-2024 09:21:34 UTC] PHP Fatal error:  Uncaught Error: Class 'WeakMap' not found in /var/www/private.com/public_html/wp-content/plugins/dynamicconditions/Public/DynamicConditionsPublic.php:90
Stack trace:
#0 /var/www/private.com/public_html/wp-content/plugins/dynamicconditions/Lib/DynamicConditions.php(165): DynamicConditions\Pub\DynamicConditionsPublic->__construct('dynamic-conditi...', '1.6.3')
#1 /var/www/private.com/public_html/wp-content/plugins/dynamicconditions/Lib/DynamicConditions.php(89): DynamicConditions\Lib\DynamicConditions->definePublicHooks()
#2 /var/www/private.com/public_html/wp-content/plugins/dynamicconditions/Lib/DynamicConditions.php(273): DynamicConditions\Lib\DynamicConditions->__construct()
#3 /var/www/private.com/public_html/wp-content/plugins/dynamicconditions/dynamic-conditions.php(70): DynamicConditions\Lib\DynamicConditions::run()
#4 /var/www/private.com/public_html/wp-settings.php(522): include_once('/var/www/...')
#5 /var/www/private.com/public_html/wp-config.php(94): require_once('/var/www/... in /var/www/private.com/public_html/wp-content/plugins/dynamicconditions/Public/DynamicConditionsPublic.php on line 90

**Comment by carolinesmedts** [comment]
Hi, I updated to 1.7.2 and have the same problem.
How can I roll back to a version that works?

**Comment by crazypsycho** [comment]
With 1.7.2 it must be a different error, because WeakMap dont exists anymore.
But we found an issue if compare by month or days is selected. This will be fixed soon.

Here you can download older versions:
https://wordpress.org/plugins/dynamicconditions/advanced/

**Comment by crazypsycho** [comment]
It is now fixed with 1.7.4
